import tkinter as tk 

class RegistrationForm(tk.Frame):
    def __init__(self, master):
        super(). __init__(master)
        
#create labels
label_registration_no = tk.Label(self, text = "Registration No:")
label_date = tk.Label(self, text = "Date: ")
label_student_details = tk.Label(self, text = "Student Details")
label_full_name = tk.Label(self, text = "Full name")
label_select_class = tk.Label(self, "Select Class")
label_date_of_birth = tk.Label(self, "Date of Birth")
label_religion = tk.Label(self, "Religion")
label_gender = tk.Label(self, "Gender")
label_class = tk.Label(self, "Class")
label_skills = tk.Label(self, "Skills")
label_upload = tk.Label(self, "Upload")
label_save = tk.Label(self, "Save")
label_parent_details = tk.Label(self, "Parent Details")
label_father_name = tk.Label(self, "Father name")
label_mother_name = tk.Label(self, "Mother name")
label_reset = tk.Label(self, "reset")
label_occupation = tk.Label(self, "occupation")
label_exit = tk.Label(self, "Exit")

#create entries
entry_registraion_no = tk.Entry(self)
entry_date = tk.Entry(self)
entry_full_name = tk.Entry(self)
entry_select_class = tk.Combobox(self)
entry_select_class['values'] = ['Class1 1', 'Class 2', 'Class 3', 'Class 4', 'Class 5', 'Class 6', 'Class 7', 'Class 8', 'Class 9', 'Class 10']
entry_date_of_birth = tk.Entry(self)
entry_religion = tk.Entry(self)
entry_gender = tk.Entry(self)
entry_class = tk.Entry(self)
entry_skills = tk.Entry(self)
entry_upload = tk.Button(self, text = "Upload")
entry_save = tk.Button(self, text = "save")
entry_reset = tk.Button(self, text = "reset")
entry_parent_details = tk.LabelFrame(self, text = "Parent's Details")
entry_father_name = tk.Entry(entry_parent_details)
entry_mother_name = tk.Entry(entry_parent_details)
entry_occupation = tk.Entry(entry_parent_details)
entry_exit = tk.Button(self, text = 'Exit')

#Grid layout
label_registration_no.grid(row = 0, column = 0)
entry_registraion_no.grid(row = 0, column = 1)
label_date.grid(row = 1, column = 0)
entry_date.grid(row = 1, column = 1)
label_student_datails.grid(row = 2, column = 0, columnspan = 2)
label_full_name.grid(row = 3, column = 0)
entry_full_name.grid(row = 3, column = 1)
label_select_class.grid(row = 4, column = 0)
entry_select_class.grid(row = 4, column = 1)
label_date_of_birth.grid(row = 5, column = 0)
entry_date_of_birth.grid(row = 5, column = 1)
label_religion.grid(row = 6, column = 0)
entry_religion.grid(row = 6, column = 1)
label_gender.grid(row = 7, column = 0)
entry_gender.grid(row = 7, column = 1)
label_class.grid(row = 8, column = 0)
entry_class.grid(row = 8, column = 1)